apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  config.ini: |
    [mysql]
    host=db
    port=3306
    db=testdb
    user=root
    passwd=testroot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        identity_template: "true"
        app: apps
    spec:
      containers:
        - image: tsidentity/tornjak-example-python:v0.1
          imagePullPolicy: Always
          name: py
          ports:
            - containerPort: 5000
          resources: {}
          volumeMounts:
          - mountPath: /app/config.ini
            name: db-config
            subPath: config.ini
      restartPolicy: Always
      volumes:
        - name: db-config
          configMap:
            name: db-config
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: apps
spec:
  type: NodePort
  selector:
    app: apps
  ports:
    - name: "8000"
      port: 8000
      targetPort: 5000
status:
  loadBalancer: {}