apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: workload-identity-tutorial
data:
  config.ini: |
    [mysql]
    host=db
    port=3306
    db=testdb
    user=root
    passwd=testroot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: py
  namespace: workload-identity-tutorial
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        identity_template: "true"
        app: py
    spec:
      containers:
        - image: tsidentity/tornjak-example-python:v0.1
          imagePullPolicy: Always
          name: py
          ports:
            - containerPort: 5000
          resources: {}
          volumeMounts:
          - mountPath: /app/config.ini
            name: db-config
            subPath: config.ini
      restartPolicy: Always
      volumes:
        - name: db-config
          configMap:
            name: db-config
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: py
  namespace: workload-identity-tutorial
spec:
  type: ClusterIP
  selector:
    app: py
  ports:
    - name: "8000"
      port: 8000
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: py
  namespace: workload-identity-tutorial
  annotations:
    route.openshift.io/termination: edge
spec:
  rules:
  - host: py.$APP_DOMAIN
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: py
            port:
              number: 8000